"""OpenAI ChatKit response types (SSE events).

This module provides ChatKit-compatible response types. It attempts to import from the official `chatkit` library

For the complete type definitions, see:
https://github.com/openai/chatkit-python/blob/main/chatkit/types.py
"""

from chatkit.actions import Action
from chatkit.errors import ErrorCode

# Try to import from official library first
from chatkit.types import (
    ActiveStatus,
    Annotation,
    AssistantMessageContent,
    AssistantMessageContentPartAdded,
    AssistantMessageContentPartAnnotationAdded,
    AssistantMessageContentPartDone,
    AssistantMessageContentPartTextDelta,
    AssistantMessageItem,
    BaseTask,
    ClientToolCallItem,
    ClosedStatus,
    CustomSummary,
    CustomTask,
    DurationSummary,
    EndOfTurnItem,
    EntitySource,
    ErrorEvent,
    FileSource,
    FileTask,
    HiddenContextItem,
    IconName,
    ImageTask,
    LockedStatus,
    NoticeEvent,
    Page,
    ProgressUpdateEvent,
    SearchTask,
    Source,
    SourceBase,
    Task,
    TaskItem,
    ThoughtTask,
    Thread,
    ThreadCreatedEvent,
    ThreadItem,
    ThreadItemAddedEvent,
    ThreadItemDoneEvent,
    ThreadItemRemovedEvent,
    ThreadItemReplacedEvent,
    ThreadItemUpdate,
    ThreadItemUpdated,
    ThreadMetadata,
    ThreadStatus,
    ThreadStreamEvent,
    ThreadUpdatedEvent,
    URLSource,
    UserMessageItem,
    WidgetComponentUpdated,
    WidgetItem,
    WidgetRootUpdated,
    WidgetStreamingTextValueDelta,
    Workflow,
    WorkflowItem,
    WorkflowSummary,
    WorkflowTaskAdded,
    WorkflowTaskUpdated,
)

__all__ = [
    # Stream event types
    'ThreadStreamEvent',
    'ThreadCreatedEvent',
    'ThreadUpdatedEvent',
    'ThreadItemDoneEvent',
    'ThreadItemAddedEvent',
    'ThreadItemUpdated',
    'ThreadItemRemovedEvent',
    'ThreadItemReplacedEvent',
    'ProgressUpdateEvent',
    'ErrorEvent',
    'NoticeEvent',
    # Thread item update types
    'AssistantMessageContentPartAdded',
    'AssistantMessageContentPartTextDelta',
    'AssistantMessageContentPartAnnotationAdded',
    'AssistantMessageContentPartDone',
    'WidgetStreamingTextValueDelta',
    'WidgetRootUpdated',
    'WidgetComponentUpdated',
    'WorkflowTaskAdded',
    'WorkflowTaskUpdated',
    'ThreadItemUpdate',
    # Thread and thread item types
    'Thread',
    'ThreadMetadata',
    'ThreadItem',
    'ThreadStatus',
    'ActiveStatus',
    'LockedStatus',
    'ClosedStatus',
    'UserMessageItem',
    'AssistantMessageItem',
    'ClientToolCallItem',
    'WidgetItem',
    'TaskItem',
    'WorkflowItem',
    'EndOfTurnItem',
    'HiddenContextItem',
    # Assistant message content
    'AssistantMessageContent',
    'Annotation',
    # Workflow and task types
    'Workflow',
    'WorkflowSummary',
    'CustomSummary',
    'DurationSummary',
    'Task',
    'BaseTask',
    'CustomTask',
    'SearchTask',
    'ThoughtTask',
    'FileTask',
    'ImageTask',
    # Source types
    'Source',
    'SourceBase',
    'FileSource',
    'URLSource',
    'EntitySource',
    # Actions
    'Action',
    # Misc types
    'IconName',
    'ErrorCode',
    'Page',
]
