from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from PIL.Image import Image as PILImage

class Chat:
    def __init__(self, messages: list[dict[str, Any]] | None = None) -> None: ...
    def add_system_message(self, content: str) -> None: ...
    def add_user_message(self, content: str | Sequence[str | Image]) -> None: ...
    def add_assistant_message(self, content: str | list[str | Image]) -> None: ...
    def extend(self, messages: list[dict[str, Any]]) -> None: ...
    def append(self, message: dict[str, Any]) -> None: ...
    def pop(self) -> dict[str, Any] | None: ...

class Image:
    def __init__(self, image: PILImage) -> None: ...
