name: 🐛 Pydantic AI Bug
description: Report a bug or unexpected behavior in Pydantic AI
labels: ["need confirmation"]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to Pydantic AI! ✊

  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: Just making sure you're using the latest version of Pydantic AI.
      options:
        - label: I confirm that I'm using the latest version of Pydantic AI
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. 🙏
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.

      placeholder: |
        from pydantic_ai import Agent

        ...
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Python, Pydantic AI & LLM client version
      description: |
        Which version of Python, Pydantic and LLM client are you using?
      render: Text
    validations:
      required: true
