name: ðŸ› Pydantic AI Bug
description: Report a bug or unexpected behavior in Pydantic AI
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to Pydantic AI! âœŠ

        Please provide as much information as possible to help us reproduce and fix your issue quickly.

  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: Just making sure we're on the same page.
      options:
        - label: I'm using the [latest version](https://github.com/pydantic/pydantic-ai/releases/latest) of Pydantic AI
          required: true
        - label: I've searched for my issue in [the issue tracker](https://github.com/pydantic/pydantic-ai/issues) before opening this issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        - **A line of code is worth a thousand words**: you can include minimal, reproducible example code below.
        - **A trace is worth a thousand log lines**: you can link to a [Pydantic Logfire](https://ai.pydantic.dev/logfire) trace below.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Minimal, Reproducible Example
      description: >
        If at all possible, please add a self-contained,
        [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
        that demonstrates the bug.

        (This will be automatically formatted as code, so no need for backticks.)

      placeholder: |
        from pydantic_ai import Agent

        ...
      render: Python

  - type: input
    id: logfire_trace
    attributes:
      label: Logfire Trace
      description: >
        If at all possible, please capture the agent run or model request leading up to the bug or error using [Pydantic Logfire](https://ai.pydantic.dev/logfire)
        and share a link to the [public trace](https://logfire.pydantic.dev/docs/guides/web-ui/public-traces/) here.

  - type: textarea
    id: version
    attributes:
      label: Python, Pydantic AI & LLM client version
      description: |
        Which version of Python, Pydantic AI, and LLM provider SDK are you using?
      value: |
        - Python:
        - Pydantic AI:
        - LLM provider SDK:
    validations:
      required: true
