name: 🚀 Pydantic AI Feature Request
description: "Suggest a new feature for Pydantic AI"
labels: ["feature request"]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to Pydantic AI! ✊

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give as much detail as possible about the feature you would like to suggest. 🙏

        You might like to add:
        * A demo of how code might look when using the feature
        * Your use case(s) for the feature
        * Reference to other projects that have a similar feature
    validations:
      required: true
