// inline src/prepare_env.py into src/prepareEnvCode.js
import * as path from '@std/path'

if (!import.meta.dirname) {
  throw new Error(
    'import.meta.dirname is not defined, unable to load prepare_env.py',
  )
}

const srcDir = path.join(import.meta.dirname, 'src')
const prepareEnvSrc = path.join(srcDir, 'prepare_env.py')
const toolInjectionSrc = path.join(srcDir, 'tool_injection.py')
const dst = path.join(srcDir, 'prepareEnvCode.ts')

let prepareEnvCode = await Deno.readTextFile(prepareEnvSrc)
let toolInjectionCode = await Deno.readTextFile(toolInjectionSrc)

prepareEnvCode = prepareEnvCode.replace(/\\/g, '\\\\')
toolInjectionCode = toolInjectionCode.replace(/\\/g, '\\\\')

const jsCode = `\
// DO NOT EDIT THIS FILE DIRECTLY, INSTEAD RUN "deno run build"
export const preparePythonCode = \`${prepareEnvCode}\`

export const toolInjectionCode = \`${toolInjectionCode}\`
`
await Deno.writeTextFile(dst, jsCode)
