name: GitHub Agent

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Run GitHub Agent
        uses: kludex/github-agent@167f586188619cdeca65528df34d804b0a4c7a18 # main 2025-05-14
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
